# Generated by Django 4.0.3 on 2022-03-03 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_portfolio_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='descriptions',
            new_name='description',
        ),
    ]
